[package]
name = "blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
serde = {version = "1.0.228" , features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
sha256 = "1.6.0"
